### ISSUE TITLE
How to hook in docstring formatter?

### ISSUE THREAD

**Issue by sirherrbatka** [Shinmera/documentation-utils#1]
This needs to be somehow customizable. I suggest trying approach it in the following way.
Currently define-docs works like this:
```common-lisp
(docs:define-docs
  (my-function "Some documentation"))
```
This should continue to be valid form for the sake of backward compatibility and simplicity. However, when user want's to forward document generation, he should specify how this should be done. I suggest following syntax as any extension.
```common-lisp
(docs:define-docs
  (my-function my-formatter :description "Some documentation" :side-effects "Does alter everything"))
```
Where my-formatter is instance of object that dispatches relevant methods and produces string as a result. Does that sound fine?

**Comment by Shinmera** [comment]
Your suggested example is not possible with current semantics, as anything but the last element in a doc expression is reserved for the identifier. Besides that, don't you think it would be incredibly cumbersome to have to specify the formatter for every definition?

How about something like this instead:
```common-lisp
(docs:define-docs
  :format my-formatter
  (function foo "Some documentation

Side effects:
Does alter everything"))
```
where your formatter is per-define-docs and automatically extracts the relevant sections from the string?

Alternatively, if you must have structure in your documentation parts, we'd either have to make the last element another list, or introduce some kind of special symbol (like `:-`) that denotes the end of the identifier

**Comment by sirherrbatka** [comment]
Sounds fine.

**Comment by sirherrbatka** [comment]
Ok, I got it, more or less. What troubles me is how to approach formatting style for individual objects.

My point is that the order of paragraphs in a docstring is of a significant importance. In docstample order was defined in per type basis (so, for instance, there was a separate order for function and for variable). However, in this project, I don't really have a good way of transferring information about the object type (and therefore expected paragraphs) down to formatter. I suggest to ignore this issue for now and use unified order for every object type, as well as allow to use every paragraph type at all times. This would mean that it is completely fine to use :return in a class docstring. Not ideal, but simple.

**Comment by Shinmera** [comment]
I don't really understand what paragraph order or any kind of formatting has to do with anything at all regarding this specific enhancement.

All that needs to be done is provide an extensible mechanism that sits between the `define-docs` expressions and the `setf documentation` forms to translate the docstring however one requires.

**Comment by sirherrbatka** [comment]
Yeah, the question remains: how to translate the docstring. It is pointless to (for example) check if every function has obligatory side-effects section just after description section manually as it quickly becomes overwhelming. In such case, it is reasonable to put "Side-Effects: None" information in docstring if not explicitly provided by the programmer as it may be documentation convention of a particular project. 

On the other hand, it makes little sense to put Side-Effects information in class docstring. Perhaps even signaling error would be the right thing to do.
