### ISSUE TITLE
exporting formatter causing issues

### ISSUE THREAD

**Issue by cbaggers** [Shinmera/documentation-utils#4]
http://report.quicklisp.org/2018-02-24/failure-report/cepl.html#cepl

> Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING 
> {10006105B3}>: Can't inherit "FORMATTER" from "DOCUMENTATION-UTILS", it is inherited from 
> "COMMON-LISP"

**Comment by Shinmera** [comment]
Indeed. Why did you `use` documentation-utils?

**Comment by cbaggers** [comment]
for `define-docs`

**Comment by Shinmera** [comment]
Just write `docs:define-docs`.

**Comment by cbaggers** [comment]
Fine, but odd. It's pretty common to use packages, might be worth adding a warning to the readme or something

**Comment by Shinmera** [comment]
I would say it's not advisable to use packages unless there's a significant amount of symbols that make it worth it.

**Comment by Shinmera** [comment]
Anyway, I'd also be open to suggestions for how to avoid the name conflict.

**Comment by sirherrbatka** [comment]
Let's find another name for formatter. Doc-formatter, for instance. Or composer.

**Comment by Shinmera** [comment]
Renamed to `documentation-formatter`, to be in line with `documentation-translator` and `documentation-test`.
