### ISSUE TITLE
CL:FIND-METHOD should probably take a list of class objects as specializers, not a list of symbols (toolkit.lisp L129)

### ISSUE THREAD

**Issue by tankrim** [Shinmera/documentation-utils#6]
Hello,

The following code, in Lispworks 7 linux-x64, causes
"Error: No method found: #<STANDARD-GENERIC-FUNCTION CREATE-APP 4100027374>,(:AROUND),(T T)."
to be signaled, while it works find in SBCL and CCL.

```
(documentation-utils:define-docs
  (method create-app :around ((id t) (country-code t))
    "Return an instance of a `vanilla-app'+`final-app' subclass, constructed with..."))
```

Reading up on CL:FIND-METHOD
(http://www.lispworks.com/documentation/lw61/CLHS/Body/f_find_m.htm)
it would seem that the specializers (in your code the "clean-specs")
should be a list of class objects, not a list of symbols.

Indeed, changing the form on line 129 of toolkit.lisp (https://github.com/Shinmera/documentation-utils/blob/98630dd5f7e36ae057fa09da3523f42ccb5d1f55/toolkit.lisp#L129) like so:

```
`(documentation (find-method #',func ',qualifiers ',(mapcar #'find-class clean-specs)) 't)
```

makes my code compile and load fine in the aforementioned Lispworks, as well as continuing to work in SBCL and CCL.

**Comment by Shinmera** [comment]
Thanks for the report!
